version: 2
jobs:
  build:
    docker:
    - image: circleci/node:9.11.1
    - image: circleci/node:10-browsers

    working_directory: ~/event-boardz-app

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "yarn.lock" }}

    - run:
        name: Setting up angular cli
        command: yarn add @angular/cli@6.2.4
    - run:
        name: Start xvfb
        command: sh -e /etc/init.d/xvfb start
    - run: yarn test
    - run: yarn build

    - store_artifacts:
        path: dist/event-boardz-app

